apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: pfi-helm-charts/fluentd
    repoURL: 494495723522.dkr.ecr.us-east-1.amazonaws.com
    targetRevision: "1.12.4"
    helm:
      releaseName: fluentd
      # valueFiles: ["values.yaml"] # resolved against source.repoURL and source.path
      # parameters:
      #   - name: commonLabels
      #     value:
      #       foo: bar
      values: |
        commonLabels:
          foo: bar
  destination:
    namespace: default
    name: "in-cluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
