apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: eugen-belskyi
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "*"
    helm:
      releaseName: postgresql
      # valueFiles: ["values.yaml"] # resolved against source.repoURL and source.path
      # parameters:
      #   - name: commonLabels
      #     value:
      #       foo: bar
      values: |
        commonLabels:
          foo: bar
  destination:
    namespace: deus
    name: "arn:aws:eks:us-east-1:494495723522:cluster/eks-lula3ydp"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
