apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
  name: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
status: {}
