apiVersion: apps/v1
kind: Deployment
annotations:
  argocd.argoproj.io/sync-wave: "-1"
metadata:
  labels:
    app: app-1
  name: app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          command:
            - "/bin/sh -c sleep 2000"
status: {}
