apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-2
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo-2
  template:
    metadata:
      labels:
        app: rollouts-demo-2
    spec:
      containers:
      - name: rollouts-demo-2
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m

---
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/test-ext"
type: Opaque
data:
  password: <password>
  username: <username>
