apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd-helm
  namespace: argocd
spec:
  project: eugen-belskyi
  source:
    chart: fluentd
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: "*"
    helm:
      releaseName: fluentd-helm
  destination:
    namespace: deus
    name: "arn:aws:eks:us-east-1:494495723522:cluster/eks-lula3ydp"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
