apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-2
  namespace: argocd
spec:
  destination:
    name: "arn:aws:eks:us-east-1:494495723522:cluster/eks-lula3ydp"
    namespace: istio-system
  project: eugen-belskyi
  source:
    chart: base
    helm:
      releaseName: istio-base-2
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: 1.13.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
