apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deus-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: deus
    name: "arn:aws:eks:us-east-1:494495723522:cluster/eks-lula3ydp"
  source:
    path: configs/app-1
    repoURL: https://github.com/eugenbelsky/argo-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
